a = input('Digite algo')
print('o tipo primitivo desse valor é',type(a))
print('é numérico?', a.isnumeric())
print('so tem espaços',a.isspace())
print('é alfanumérico',a.isalnum())
print('é alfabético', a.isalpha())
print('Está em maiúsculas',a.isupper())
print('Está em minúsculas',a.islower())
print('Está capitalizada',a.istitle())
